ACCOUNT_DB_HOST = '127.0.0.1'
ACCOUNT_DB_PORT = '3306'
ACCOUNT_DB_DATABASE = 'test'
ACCOUNT_DB_USER = 'root'
ACCOUNT_DB_PASSWORD = 'flsnrtm@1234'

#SQLALCHEMY
SQLALCHEMY_DATABASE_URI = 'mysql+pymysql://'+ACCOUNT_DB_USER+':'+ACCOUNT_DB_PASSWORD+'@'+ACCOUNT_DB_HOST+':'+ACCOUNT_DB_PORT+'/'+ACCOUNT_DB_DATABASE
# 비지니스 로직이 끝날때 Commit 실행(DB반영)
SQLALCHEMY_COMMIT_ON_TEARDOWN = True
# 수정사항에 대한 TRACK
SQLALCHEMY_TRACK_MODIFICATIONS = True